[workspace]
authors = ["Mike Smyth <Mike.M.Smyth@jpl.nasa.gov>"]
channels = ["conda-forge", "/Users/smyth/afids-conda-package/afids-conda-channel"]
name = "build-pixi"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
configure = "/Users/smyth/Afids/geocal/env//../configure --prefix=$CONDA_PREFIX"

[dependencies]
afids = "*"
afids-development-tools = "*"
