from __future__ import annotations
from .vicar_interface import VicarInterface
from .sqlite_shelf import write_shelve
from geocal_swig import (  # type: ignore
    IbisFile,
    VicarImageCoordinate,
    TiePointCollection,
    VicarLiteRasterImage,
)
import os
import numpy as np
from pathlib import Path


class _warp(VicarInterface):
    """Call gtwarpxd"""

    def __init__(
        self,
        img_in: str | os.PathLike[str],
        img_out: str | os.PathLike[str],
        ref_img: str | os.PathLike[str],
        tpcol: TiePointCollection,
        image_index: int = 0,
        nah: int = 100,
        nav: int = 100,
        polyfit: str | None = None,
        tpgrid_out: str | os.PathLike[str] | None = None,
        interp: str = "bilin",
        log_file: str | os.PathLike[str] | None = None,
        run_dir_name: str | os.PathLike[str] | None = None,
        quiet: bool = True,
    ) -> None:
        VicarInterface.__init__(self)
        self.title = "warp"
        self.log_file = Path(log_file) if log_file is not None else None
        self.run_dir_name = Path(run_dir_name) if run_dir_name is not None else None
        self.tpcol = tpcol
        self.image_index = image_index
        if tpgrid_out:
            self.tpgrid_out: Path | None = Path(tpgrid_out).absolute()
        else:
            self.tpgrid_out = None
        self.ref_img = Path(ref_img).absolute()
        self.input = [Path(img_in), Path(ref_img)]
        self.output = [
            Path(img_out),
        ]
        self.img_out = Path(img_out).absolute()
        self.print_output = not quiet
        self.before_body = """
local img_in string
local img_out string
local ref_img string
local nah int
local nav int
local polyfit string
local interp string
local distort string
local gridout string
"""
        self.cmd = 'let img_in="%s"\n' % Path(img_in).name
        self.cmd += 'let ref_img="%s"\n' % self.ref_img.name
        self.cmd += 'let img_out="%s"\n' % self.img_out.name
        self.cmd += 'let distort="distort.ibis"\n'
        self.cmd += "let nah=%d\n" % nah
        self.cmd += "let nav=%d\n" % nav
        self.cmd += 'let polyfit="%s"\n' % (polyfit if polyfit else "")
        self.cmd += 'let interp="%s"\n' % interp
        self.cmd += 'let gridout="gridout"\n'
        self.cmd += """
gtwarpxd inp=&img_in out=&img_out ref=&ref_img 'coverref interp=&interp +
        nah=&nah nav=&nav gridout=&gridout +
        distort=(&distort,,,,) dcols=(1,2,3,4) polyfit=("&polyfit",,,,) +
        echo="yes"
"""
        self.timing = False
        if self.run_dir_name is not None:
            self.keep_run_dir = True
        self.vicar_run()

    def post_run(self) -> None:
        if self.tpgrid_out:
            tpcol = TiePointCollection()
            f = VicarLiteRasterImage(self.img_out)
            tpcol.add_ibis_file("gridout1", f, None)
            write_shelve(self.tpgrid_out, tpcol)

    def pre_run(self) -> None:
        npts = np.count_nonzero(
            [tp.image_coordinate(self.image_index) for tp in self.tpcol]
        )
        data = np.empty((npts, 4))
        i = 0
        ref = VicarLiteRasterImage(self.ref_img)
        for tp in self.tpcol:
            ic = tp.image_coordinate(self.image_index)
            if ic:
                ic = VicarImageCoordinate(ic)
                data[i, 2] = ic.line
                data[i, 3] = ic.sample
                ic2 = VicarImageCoordinate(ref.coordinate(tp.ground_location))
                data[i, 0] = ic2.line
                data[i, 1] = ic2.sample
                i += 1
        IbisFile.create("distort.ibis", data)


def warp_image(
    img_in: str | os.PathLike[str],
    img_out: str | os.PathLike[str],
    ref_img: str | os.PathLike[str],
    tpcol: TiePointCollection,
    image_index: int = 0,
    nah: int = 100,
    nav: int = 100,
    polyfit: str | None = None,
    tpgrid_out: str | os.PathLike[str] | None = None,
    interp: str = "bilin",
    log_file: str | os.PathLike[str] | None = None,
    run_dir_name: str | os.PathLike[str] | None = None,
    quiet: bool = True,
) -> None:
    """This is a wrapper around gtwarpxd. We warp the vicar file input
    img_in, writing out as img_out. This matches the given ref_img. This
    take the set of tiepoint in tpcol (e.g., generated by
    TiePointCollectPicmtch).

    nah and nav are the number of grid cells in the horizontal and vertical
    direction used by gtwarpxd.

    Interpolation should be noin, bilin, cubcon or cubsplin.

    Polyfit can override the triangulation surface fit with a
    polynomial fit. It should be empty, linear, keystone, quad or
    cubic.
    """
    _ = _warp(
        img_in,
        img_out,
        ref_img,
        tpcol,
        image_index=image_index,
        nah=nah,
        nav=nav,
        polyfit=polyfit,
        interp=interp,
        tpgrid_out=tpgrid_out,
        log_file=log_file,
        run_dir_name=run_dir_name,
        quiet=quiet,
    )


__all__ = ["warp_image"]
