# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
from ._swig_wrap import _air_mspi_igc

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _air_mspi_igc.SWIG_PyInstanceMethod_New
_swig_new_static_method = _air_mspi_igc.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

SWIG_MODULE_ALREADY_DONE = _air_mspi_igc.SWIG_MODULE_ALREADY_DONE
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _air_mspi_igc.delete_SwigPyIterator
    value = _swig_new_instance_method(_air_mspi_igc.SwigPyIterator_value)
    incr = _swig_new_instance_method(_air_mspi_igc.SwigPyIterator_incr)
    decr = _swig_new_instance_method(_air_mspi_igc.SwigPyIterator_decr)
    distance = _swig_new_instance_method(_air_mspi_igc.SwigPyIterator_distance)
    equal = _swig_new_instance_method(_air_mspi_igc.SwigPyIterator_equal)
    copy = _swig_new_instance_method(_air_mspi_igc.SwigPyIterator_copy)
    next = _swig_new_instance_method(_air_mspi_igc.SwigPyIterator_next)
    __next__ = _swig_new_instance_method(_air_mspi_igc.SwigPyIterator___next__)
    previous = _swig_new_instance_method(_air_mspi_igc.SwigPyIterator_previous)
    advance = _swig_new_instance_method(_air_mspi_igc.SwigPyIterator_advance)
    __eq__ = _swig_new_instance_method(_air_mspi_igc.SwigPyIterator___eq__)
    __ne__ = _swig_new_instance_method(_air_mspi_igc.SwigPyIterator___ne__)
    __iadd__ = _swig_new_instance_method(_air_mspi_igc.SwigPyIterator___iadd__)
    __isub__ = _swig_new_instance_method(_air_mspi_igc.SwigPyIterator___isub__)
    __add__ = _swig_new_instance_method(_air_mspi_igc.SwigPyIterator___add__)
    __sub__ = _swig_new_instance_method(_air_mspi_igc.SwigPyIterator___sub__)
    def __iter__(self):
        return self

# Register SwigPyIterator in _air_mspi_igc:
_air_mspi_igc.SwigPyIterator_swigregister(SwigPyIterator)
SHARED_PTR_DISOWN = _air_mspi_igc.SHARED_PTR_DISOWN

import os

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_serialization(data):
    return geocal_swig.serialize_function.serialize_read_binary(data)

def _new_from_serialization_dir(dir, data):
    curdir = os.getcwd()
    try:
      os.chdir(dir)
      return geocal_swig.serialize_function.serialize_read_binary(data)
    finally:
      os.chdir(curdir)


def _new_vector(cls, version, lst):
    '''Create a vector from a list.'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    for i in lst:
       inst.append(i)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import geocal_swig.ipi_image_ground_connection
import geocal_swig.image_ground_connection
import geocal_swig.generic_object
import geocal_swig.with_parameter
import geocal_swig.geocal_exception
import geocal_swig.observer
import geocal_swig.raster_image_tiled_file
import geocal_swig.raster_image_variable
import geocal_swig.quaternion_camera
class AirMspiIgc(geocal_swig.ipi_image_ground_connection.IpiImageGroundConnection):
    r"""

    This is an ImageGroundConnection for AirMspi.

    C++ includes: air_mspi_igc.h 
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""

        AirMspiIgc::AirMspiIgc(const boost::shared_ptr< Orbit > &Orb, const boost::shared_ptr<
        MspiCamera > &Cam, const boost::shared_ptr< MspiGimbal > &Gim, const
        boost::shared_ptr< Dem > &Dem, const std::string &L1b1_file_name, int
        Min_l1b1_line, int Max_l1b1_line, const std::string
        &Swath_to_use="660-I", const std::string &Title="Image", int
        Dem_resolution=10, int Tile_number_line=-1, int Tile_number_sample=-1,
        unsigned int Number_tile=4)
        Constructor.

        This variation of the constructor directly takes the information
        needed to construct the object, rather than reading this from the
        master configuration file. 
        """
        _air_mspi_igc.AirMspiIgc_swiginit(self, _air_mspi_igc.new_AirMspiIgc(*args))
    _v_band = _swig_new_instance_method(_air_mspi_igc.AirMspiIgc__v_band)

    @property
    def band(self):
        return self._v_band()

    @band.setter
    def band(self, value):
      self._v_band(value)

    _v_orbit = _swig_new_instance_method(_air_mspi_igc.AirMspiIgc__v_orbit)

    @property
    def orbit(self):
        return self._v_orbit()

    _v_time_table = _swig_new_instance_method(_air_mspi_igc.AirMspiIgc__v_time_table)

    @property
    def time_table(self):
        return self._v_time_table()

    _v_camera = _swig_new_instance_method(_air_mspi_igc.AirMspiIgc__v_camera)

    @property
    def camera(self):
        return self._v_camera()

    _v_gimbal = _swig_new_instance_method(_air_mspi_igc.AirMspiIgc__v_gimbal)

    @property
    def gimbal(self):
        return self._v_gimbal()

    _v_l1b1_file_name = _swig_new_instance_method(_air_mspi_igc.AirMspiIgc__v_l1b1_file_name)

    @property
    def l1b1_file_name(self):
        return self._v_l1b1_file_name()


    def __reduce__(self):
      return _new_from_serialization_dir, (os.getcwd(), geocal_swig.serialize_function.serialize_write_binary(self),)

    __swig_destroy__ = _air_mspi_igc.delete_AirMspiIgc

# Register AirMspiIgc in _air_mspi_igc:
_air_mspi_igc.AirMspiIgc_swigregister(AirMspiIgc)

__all__ = ["AirMspiIgc"]


