# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
from ._swig_wrap import _geocal_gdal

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _geocal_gdal.SWIG_PyInstanceMethod_New
_swig_new_static_method = _geocal_gdal.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

SWIG_MODULE_ALREADY_DONE = _geocal_gdal.SWIG_MODULE_ALREADY_DONE
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _geocal_gdal.delete_SwigPyIterator
    value = _swig_new_instance_method(_geocal_gdal.SwigPyIterator_value)
    incr = _swig_new_instance_method(_geocal_gdal.SwigPyIterator_incr)
    decr = _swig_new_instance_method(_geocal_gdal.SwigPyIterator_decr)
    distance = _swig_new_instance_method(_geocal_gdal.SwigPyIterator_distance)
    equal = _swig_new_instance_method(_geocal_gdal.SwigPyIterator_equal)
    copy = _swig_new_instance_method(_geocal_gdal.SwigPyIterator_copy)
    next = _swig_new_instance_method(_geocal_gdal.SwigPyIterator_next)
    __next__ = _swig_new_instance_method(_geocal_gdal.SwigPyIterator___next__)
    previous = _swig_new_instance_method(_geocal_gdal.SwigPyIterator_previous)
    advance = _swig_new_instance_method(_geocal_gdal.SwigPyIterator_advance)
    __eq__ = _swig_new_instance_method(_geocal_gdal.SwigPyIterator___eq__)
    __ne__ = _swig_new_instance_method(_geocal_gdal.SwigPyIterator___ne__)
    __iadd__ = _swig_new_instance_method(_geocal_gdal.SwigPyIterator___iadd__)
    __isub__ = _swig_new_instance_method(_geocal_gdal.SwigPyIterator___isub__)
    __add__ = _swig_new_instance_method(_geocal_gdal.SwigPyIterator___add__)
    __sub__ = _swig_new_instance_method(_geocal_gdal.SwigPyIterator___sub__)
    def __iter__(self):
        return self

# Register SwigPyIterator in _geocal_gdal:
_geocal_gdal.SwigPyIterator_swigregister(SwigPyIterator)
SHARED_PTR_DISOWN = _geocal_gdal.SHARED_PTR_DISOWN

import os

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_serialization(data):
    return geocal_swig.serialize_function.serialize_read_binary(data)

def _new_from_serialization_dir(dir, data):
    curdir = os.getcwd()
    try:
      os.chdir(dir)
      return geocal_swig.serialize_function.serialize_read_binary(data)
    finally:
      os.chdir(curdir)


def _new_vector(cls, version, lst):
    '''Create a vector from a list.'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    for i in lst:
       inst.append(i)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import geocal_swig.generic_object
import geocal_swig.with_parameter
import geocal_swig.geocal_exception
class GdalBase(geocal_swig.generic_object.GenericObject):
    r"""

    Base class of Gdal<T>.

    This contains the portion that doesn't depend on T.

    C++ includes: geocal_gdal.h 
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    _v_map_info = _swig_new_instance_method(_geocal_gdal.GdalBase__v_map_info)

    @property
    def map_info(self):
        return self._v_map_info()

    @map_info.setter
    def map_info(self, value):
      self._v_map_info(value)

    _v_raster_band = _swig_new_instance_method(_geocal_gdal.GdalBase__v_raster_band)

    @property
    def raster_band(self):
        return self._v_raster_band()

    _v_linear_unit_name = _swig_new_instance_method(_geocal_gdal.GdalBase__v_linear_unit_name)

    @property
    def linear_unit_name(self):
        return self._v_linear_unit_name()

    _v_linear_unit_scale = _swig_new_instance_method(_geocal_gdal.GdalBase__v_linear_unit_scale)

    @property
    def linear_unit_scale(self):
        return self._v_linear_unit_scale()

    close = _swig_new_instance_method(_geocal_gdal.GdalBase_close)
    _v_is_closed = _swig_new_instance_method(_geocal_gdal.GdalBase__v_is_closed)

    @property
    def is_closed(self):
        return self._v_is_closed()

    flush = _swig_new_instance_method(_geocal_gdal.GdalBase_flush)
    _v_rpc = _swig_new_instance_method(_geocal_gdal.GdalBase__v_rpc)

    @property
    def rpc(self):
        return self._v_rpc()

    __str__ = _swig_new_instance_method(_geocal_gdal.GdalBase___str__)
    driver_count = _swig_new_static_method(_geocal_gdal.GdalBase_driver_count)
    driver_short_name = _swig_new_static_method(_geocal_gdal.GdalBase_driver_short_name)
    driver_long_name = _swig_new_static_method(_geocal_gdal.GdalBase_driver_long_name)
    driver_help_url = _swig_new_static_method(_geocal_gdal.GdalBase_driver_help_url)
    driver_option_list = _swig_new_static_method(_geocal_gdal.GdalBase_driver_option_list)

    def __init__(self):
        _geocal_gdal.GdalBase_swiginit(self, _geocal_gdal.new_GdalBase())
    __swig_destroy__ = _geocal_gdal.delete_GdalBase

# Register GdalBase in _geocal_gdal:
_geocal_gdal.GdalBase_swigregister(GdalBase)
gdal_driver_name = _geocal_gdal.gdal_driver_name

__all__ = ["GdalBase","gdal_driver_name"]


