# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
from ._swig_wrap import _image_point_display

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _image_point_display.SWIG_PyInstanceMethod_New
_swig_new_static_method = _image_point_display.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

SWIG_MODULE_ALREADY_DONE = _image_point_display.SWIG_MODULE_ALREADY_DONE
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _image_point_display.delete_SwigPyIterator
    value = _swig_new_instance_method(_image_point_display.SwigPyIterator_value)
    incr = _swig_new_instance_method(_image_point_display.SwigPyIterator_incr)
    decr = _swig_new_instance_method(_image_point_display.SwigPyIterator_decr)
    distance = _swig_new_instance_method(_image_point_display.SwigPyIterator_distance)
    equal = _swig_new_instance_method(_image_point_display.SwigPyIterator_equal)
    copy = _swig_new_instance_method(_image_point_display.SwigPyIterator_copy)
    next = _swig_new_instance_method(_image_point_display.SwigPyIterator_next)
    __next__ = _swig_new_instance_method(_image_point_display.SwigPyIterator___next__)
    previous = _swig_new_instance_method(_image_point_display.SwigPyIterator_previous)
    advance = _swig_new_instance_method(_image_point_display.SwigPyIterator_advance)
    __eq__ = _swig_new_instance_method(_image_point_display.SwigPyIterator___eq__)
    __ne__ = _swig_new_instance_method(_image_point_display.SwigPyIterator___ne__)
    __iadd__ = _swig_new_instance_method(_image_point_display.SwigPyIterator___iadd__)
    __isub__ = _swig_new_instance_method(_image_point_display.SwigPyIterator___isub__)
    __add__ = _swig_new_instance_method(_image_point_display.SwigPyIterator___add__)
    __sub__ = _swig_new_instance_method(_image_point_display.SwigPyIterator___sub__)
    def __iter__(self):
        return self

# Register SwigPyIterator in _image_point_display:
_image_point_display.SwigPyIterator_swigregister(SwigPyIterator)
SHARED_PTR_DISOWN = _image_point_display.SHARED_PTR_DISOWN

import os

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_serialization(data):
    return geocal_swig.serialize_function.serialize_read_binary(data)

def _new_from_serialization_dir(dir, data):
    curdir = os.getcwd()
    try:
      os.chdir(dir)
      return geocal_swig.serialize_function.serialize_read_binary(data)
    finally:
      os.chdir(curdir)


def _new_vector(cls, version, lst):
    '''Create a vector from a list.'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    for i in lst:
       inst.append(i)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import geocal_swig.gdal_raster_image
import geocal_swig.raster_image_tiled_file
import geocal_swig.raster_image_variable
import geocal_swig.raster_image
import geocal_swig.generic_object
import geocal_swig.with_parameter
import geocal_swig.geocal_exception
class ImagePointDisplay(geocal_swig.gdal_raster_image.GdalRasterImage):
    r"""

    This class is used to generate a display of image points.

    This is useful for example to show the difference between initial and
    final location during image matching

    C++ includes: image_point_display.h 
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""

        GeoCal::ImagePointDisplay::ImagePointDisplay(const std::string &Fname, const std::string &Driver_name, int
        Number_line, int Number_sample, int Dt, const std::string
        &Options="", int Number_tile=4, int Tile_number_line=-1, int
        Tile_number_sample=-1)
        Constructor to write a new file. 
        """
        _image_point_display.ImagePointDisplay_swiginit(self, _image_point_display.new_ImagePointDisplay(*args))
    image_point = _swig_new_instance_method(_image_point_display.ImagePointDisplay_image_point)
    __swig_destroy__ = _image_point_display.delete_ImagePointDisplay

# Register ImagePointDisplay in _image_point_display:
_image_point_display.ImagePointDisplay_swigregister(ImagePointDisplay)

__all__ = ["ImagePointDisplay"]


