# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
from ._swig_wrap import _landsat7_global

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _landsat7_global.SWIG_PyInstanceMethod_New
_swig_new_static_method = _landsat7_global.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

SWIG_MODULE_ALREADY_DONE = _landsat7_global.SWIG_MODULE_ALREADY_DONE
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _landsat7_global.delete_SwigPyIterator
    value = _swig_new_instance_method(_landsat7_global.SwigPyIterator_value)
    incr = _swig_new_instance_method(_landsat7_global.SwigPyIterator_incr)
    decr = _swig_new_instance_method(_landsat7_global.SwigPyIterator_decr)
    distance = _swig_new_instance_method(_landsat7_global.SwigPyIterator_distance)
    equal = _swig_new_instance_method(_landsat7_global.SwigPyIterator_equal)
    copy = _swig_new_instance_method(_landsat7_global.SwigPyIterator_copy)
    next = _swig_new_instance_method(_landsat7_global.SwigPyIterator_next)
    __next__ = _swig_new_instance_method(_landsat7_global.SwigPyIterator___next__)
    previous = _swig_new_instance_method(_landsat7_global.SwigPyIterator_previous)
    advance = _swig_new_instance_method(_landsat7_global.SwigPyIterator_advance)
    __eq__ = _swig_new_instance_method(_landsat7_global.SwigPyIterator___eq__)
    __ne__ = _swig_new_instance_method(_landsat7_global.SwigPyIterator___ne__)
    __iadd__ = _swig_new_instance_method(_landsat7_global.SwigPyIterator___iadd__)
    __isub__ = _swig_new_instance_method(_landsat7_global.SwigPyIterator___isub__)
    __add__ = _swig_new_instance_method(_landsat7_global.SwigPyIterator___add__)
    __sub__ = _swig_new_instance_method(_landsat7_global.SwigPyIterator___sub__)
    def __iter__(self):
        return self

# Register SwigPyIterator in _landsat7_global:
_landsat7_global.SwigPyIterator_swigregister(SwigPyIterator)
SHARED_PTR_DISOWN = _landsat7_global.SHARED_PTR_DISOWN

import os

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_serialization(data):
    return geocal_swig.serialize_function.serialize_read_binary(data)

def _new_from_serialization_dir(dir, data):
    curdir = os.getcwd()
    try:
      os.chdir(dir)
      return geocal_swig.serialize_function.serialize_read_binary(data)
    finally:
      os.chdir(curdir)


def _new_vector(cls, version, lst):
    '''Create a vector from a list.'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    for i in lst:
       inst.append(i)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import geocal_swig.cart_lab_multifile
import geocal_swig.raster_multifile
import geocal_swig.raster_image_variable
import geocal_swig.raster_image
import geocal_swig.generic_object
import geocal_swig.with_parameter
import geocal_swig.geocal_exception
class Landsat7Global(geocal_swig.cart_lab_multifile.VicarCartLabMultifile):
    r"""

    This is used to read the global Landsat 7 data.

    The resolution varies by band. The The geolocation accuracy was
    estimated by Tom Logan at 1/3 pixel or so. Not sure how accurate this
    estimate is, perhaps Tom has a better estimate.

    The bands are the standard Landsat 7 bands:

    Band Wavelength (micrometer) Resolution (m) Band 1 - Blue 0.45-0.52 30
    Band 2 - Green 0.52-0.60 30 Band 3 - Red 0.63-0.69 30 Band 4 - Near
    Infrared (NIR) 0.77-0.90 30 Band 5 - Shortwave Infrared (SWIR) 1
    1.55-1.75 30 Band 6 - Thermal 10.40-12.50 60 Band 7 - Shortwave
    Infrared (SWIR) 2 2.09-2.35 30 Band 8 - Panchromatic .52-.90 15

    Band 6 has both a low and a high gain (Bands 61 and 62).

    C++ includes: landsat7_global.h 
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    BAND1 = _landsat7_global.Landsat7Global_BAND1
    BAND2 = _landsat7_global.Landsat7Global_BAND2
    BAND3 = _landsat7_global.Landsat7Global_BAND3
    BAND4 = _landsat7_global.Landsat7Global_BAND4
    BAND5 = _landsat7_global.Landsat7Global_BAND5
    BAND61 = _landsat7_global.Landsat7Global_BAND61
    BAND62 = _landsat7_global.Landsat7Global_BAND62
    BAND7 = _landsat7_global.Landsat7Global_BAND7
    BAND8 = _landsat7_global.Landsat7Global_BAND8

    def __init__(self, Dir, B):
        r"""

        Landsat7Global::Landsat7Global(const std::string &Dir, Band B)
        GeoCal::Landsat7Global::Landsat7Global
        Constructor.
        You provide the directory to look for Landsat 7 data, along with the
        band type. 
        """
        _landsat7_global.Landsat7Global_swiginit(self, _landsat7_global.new_Landsat7Global(Dir, B))
    _v_band = _swig_new_instance_method(_landsat7_global.Landsat7Global__v_band)

    @property
    def band(self):
        return self._v_band()


    def __reduce__(self):
    #Special handling for when we are doing boost serialization, we set
    #"this" to None
      if(self.this is None):
        return super().__reduce__()
      return _new_from_serialization, (geocal_swig.serialize_function.serialize_write_binary(self),)

    __swig_destroy__ = _landsat7_global.delete_Landsat7Global

# Register Landsat7Global in _landsat7_global:
_landsat7_global.Landsat7Global_swigregister(Landsat7Global)

__all__ = ["Landsat7Global"]


