# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
from ._swig_wrap import _mspi_gimbal

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _mspi_gimbal.SWIG_PyInstanceMethod_New
_swig_new_static_method = _mspi_gimbal.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

SWIG_MODULE_ALREADY_DONE = _mspi_gimbal.SWIG_MODULE_ALREADY_DONE
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _mspi_gimbal.delete_SwigPyIterator
    value = _swig_new_instance_method(_mspi_gimbal.SwigPyIterator_value)
    incr = _swig_new_instance_method(_mspi_gimbal.SwigPyIterator_incr)
    decr = _swig_new_instance_method(_mspi_gimbal.SwigPyIterator_decr)
    distance = _swig_new_instance_method(_mspi_gimbal.SwigPyIterator_distance)
    equal = _swig_new_instance_method(_mspi_gimbal.SwigPyIterator_equal)
    copy = _swig_new_instance_method(_mspi_gimbal.SwigPyIterator_copy)
    next = _swig_new_instance_method(_mspi_gimbal.SwigPyIterator_next)
    __next__ = _swig_new_instance_method(_mspi_gimbal.SwigPyIterator___next__)
    previous = _swig_new_instance_method(_mspi_gimbal.SwigPyIterator_previous)
    advance = _swig_new_instance_method(_mspi_gimbal.SwigPyIterator_advance)
    __eq__ = _swig_new_instance_method(_mspi_gimbal.SwigPyIterator___eq__)
    __ne__ = _swig_new_instance_method(_mspi_gimbal.SwigPyIterator___ne__)
    __iadd__ = _swig_new_instance_method(_mspi_gimbal.SwigPyIterator___iadd__)
    __isub__ = _swig_new_instance_method(_mspi_gimbal.SwigPyIterator___isub__)
    __add__ = _swig_new_instance_method(_mspi_gimbal.SwigPyIterator___add__)
    __sub__ = _swig_new_instance_method(_mspi_gimbal.SwigPyIterator___sub__)
    def __iter__(self):
        return self

# Register SwigPyIterator in _mspi_gimbal:
_mspi_gimbal.SwigPyIterator_swigregister(SwigPyIterator)
SHARED_PTR_DISOWN = _mspi_gimbal.SHARED_PTR_DISOWN

import os

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_serialization(data):
    return geocal_swig.serialize_function.serialize_read_binary(data)

def _new_from_serialization_dir(dir, data):
    curdir = os.getcwd()
    try:
      os.chdir(dir)
      return geocal_swig.serialize_function.serialize_read_binary(data)
    finally:
      os.chdir(curdir)


def _new_vector(cls, version, lst):
    '''Create a vector from a list.'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    for i in lst:
       inst.append(i)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import geocal_swig.with_parameter
import geocal_swig.generic_object
import geocal_swig.observer
class ObservableMspiGimbal(geocal_swig.generic_object.GenericObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _mspi_gimbal.delete_ObservableMspiGimbal
    add_observer_and_keep_reference = _swig_new_instance_method(_mspi_gimbal.ObservableMspiGimbal_add_observer_and_keep_reference)
    add_observer = _swig_new_instance_method(_mspi_gimbal.ObservableMspiGimbal_add_observer)
    remove_observer = _swig_new_instance_method(_mspi_gimbal.ObservableMspiGimbal_remove_observer)

# Register ObservableMspiGimbal in _mspi_gimbal:
_mspi_gimbal.ObservableMspiGimbal_swigregister(ObservableMspiGimbal)
class ObserverMspiGimbal(geocal_swig.generic_object.GenericObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mspi_gimbal.ObserverMspiGimbal_swiginit(self, _mspi_gimbal.new_ObserverMspiGimbal())
    __swig_destroy__ = _mspi_gimbal.delete_ObserverMspiGimbal
    notify_update = _swig_new_instance_method(_mspi_gimbal.ObserverMspiGimbal_notify_update)
    notify_add = _swig_new_instance_method(_mspi_gimbal.ObserverMspiGimbal_notify_add)
    notify_remove = _swig_new_instance_method(_mspi_gimbal.ObserverMspiGimbal_notify_remove)

# Register ObserverMspiGimbal in _mspi_gimbal:
_mspi_gimbal.ObserverMspiGimbal_swigregister(ObserverMspiGimbal)
class MspiGimbal(geocal_swig.with_parameter.WithParameter, ObservableMspiGimbal):
    r"""

    This handles the AirMSPI gimbal calculations.

    C++ includes: mspi_gimbal.h 
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""

        GeoCal::MspiGimbal::MspiGimbal(double Epsilon, double Psi, double Theta)
        GeoCal::MspiGimbal::MspiGimbal
        Constructor. The angles should be in degrees.

        """
        _mspi_gimbal.MspiGimbal_swiginit(self, _mspi_gimbal.new_MspiGimbal(*args))
    read_config_file = _swig_new_instance_method(_mspi_gimbal.MspiGimbal_read_config_file)
    _v_epsilon = _swig_new_instance_method(_mspi_gimbal.MspiGimbal__v_epsilon)

    @property
    def epsilon(self):
        return self._v_epsilon()

    _v_epsilon_with_derivative = _swig_new_instance_method(_mspi_gimbal.MspiGimbal__v_epsilon_with_derivative)

    @property
    def epsilon_with_derivative(self):
        return self._v_epsilon_with_derivative()

    _v_psi = _swig_new_instance_method(_mspi_gimbal.MspiGimbal__v_psi)

    @property
    def psi(self):
        return self._v_psi()

    _v_psi_with_derivative = _swig_new_instance_method(_mspi_gimbal.MspiGimbal__v_psi_with_derivative)

    @property
    def psi_with_derivative(self):
        return self._v_psi_with_derivative()

    _v_theta = _swig_new_instance_method(_mspi_gimbal.MspiGimbal__v_theta)

    @property
    def theta(self):
        return self._v_theta()

    _v_theta_with_derivative = _swig_new_instance_method(_mspi_gimbal.MspiGimbal__v_theta_with_derivative)

    @property
    def theta_with_derivative(self):
        return self._v_theta_with_derivative()

    _v_parameter_mask = _swig_new_instance_method(_mspi_gimbal.MspiGimbal__v_parameter_mask)

    @property
    def parameter_mask(self):
        return self._v_parameter_mask()

    @parameter_mask.setter
    def parameter_mask(self, value):
      self._v_parameter_mask(value)

    station_to_sc_with_derivative = _swig_new_instance_method(_mspi_gimbal.MspiGimbal_station_to_sc_with_derivative)
    station_to_sc = _swig_new_instance_method(_mspi_gimbal.MspiGimbal_station_to_sc)
    __str__ = _swig_new_instance_method(_mspi_gimbal.MspiGimbal___str__)

    def __reduce__(self):
    #Special handling for when we are doing boost serialization, we set
    #"this" to None
      if(self.this is None):
        return super().__reduce__()
      return _new_from_serialization, (geocal_swig.serialize_function.serialize_write_binary(self),)

    __swig_destroy__ = _mspi_gimbal.delete_MspiGimbal

# Register MspiGimbal in _mspi_gimbal:
_mspi_gimbal.MspiGimbal_swigregister(MspiGimbal)

__all__ = ["MspiGimbal","ObserverMspiGimbal","ObservableMspiGimbal"]


