# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.9
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (3,0,0):
    new_instancemethod = lambda func, inst, cls: _raster_image_tiled_file.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_raster_image_tiled_file', [dirname(__file__)])
        except ImportError:
            import _raster_image_tiled_file
            return _raster_image_tiled_file
        if fp is not None:
            try:
                _mod = imp.load_module('_raster_image_tiled_file', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _raster_image_tiled_file = swig_import_helper()
    del swig_import_helper
else:
    import _raster_image_tiled_file
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


try:
    import weakref
    weakref_proxy = weakref.proxy
except:
    weakref_proxy = lambda x: x


SHARED_PTR_DISOWN = _raster_image_tiled_file.SHARED_PTR_DISOWN
def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_vector(cls, version, lst):
    '''Create a vector from a list.'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    for i in lst:
       inst.append(i)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import geocal_swig.raster_image_variable
import geocal_swig.raster_image
import geocal_swig.generic_object
import geocal_swig.look_vector
class RasterImageTiledFile(geocal_swig.raster_image_variable.RasterImageVariable):
    """
    This is a RasterImage that is implemented as a TiledFile<T, 2>.

    C++ includes: raster_image_tiled_file.h 
    """
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        GeoCal::RasterImageTiledFile::RasterImageTiledFile(const boost::shared_ptr< TiledFileBase< 2 > > &D, const MapInfo &M)

        """
        _raster_image_tiled_file.RasterImageTiledFile_swiginit(self,_raster_image_tiled_file.new_RasterImageTiledFile(*args))
    def _v_tile_file_base(self):
        """
        const boost::shared_ptr<TiledFileBase<2> >& GeoCal::RasterImageTiledFile::tile_file_base_ptr() const
        Underlying data. 
        """
        return _raster_image_tiled_file.RasterImageTiledFile__v_tile_file_base(self)

    @property
    def tile_file_base(self):
        return self._v_tile_file_base()

    def flush(self):
        """
        virtual void GeoCal::RasterImageTiledFile::flush() const
        Flush data to disk. 
        """
        return _raster_image_tiled_file.RasterImageTiledFile_flush(self)

    def _v_number_swap(self):
        """
        unsigned int GeoCal::RasterImageTiledFile::number_swap() const
        Number of times we have swapped a tile since reset_number_swap called.

        """
        return _raster_image_tiled_file.RasterImageTiledFile__v_number_swap(self)

    @property
    def number_swap(self):
        return self._v_number_swap()

    def _v_number_tile(self):
        """
        int GeoCal::RasterImageTiledFile::number_tile() const
        Number of tiles. 
        """
        return _raster_image_tiled_file.RasterImageTiledFile__v_number_tile(self)

    @property
    def number_tile(self):
        return self._v_number_tile()

    def reset_number_swap(self):
        """
        void GeoCal::RasterImageTiledFile::reset_number_swap()
        Reset number of swap counter to 0. 
        """
        return _raster_image_tiled_file.RasterImageTiledFile_reset_number_swap(self)

    __swig_destroy__ = _raster_image_tiled_file.delete_RasterImageTiledFile
RasterImageTiledFile._v_tile_file_base = new_instancemethod(_raster_image_tiled_file.RasterImageTiledFile__v_tile_file_base,None,RasterImageTiledFile)
RasterImageTiledFile.flush = new_instancemethod(_raster_image_tiled_file.RasterImageTiledFile_flush,None,RasterImageTiledFile)
RasterImageTiledFile._v_number_swap = new_instancemethod(_raster_image_tiled_file.RasterImageTiledFile__v_number_swap,None,RasterImageTiledFile)
RasterImageTiledFile._v_number_tile = new_instancemethod(_raster_image_tiled_file.RasterImageTiledFile__v_number_tile,None,RasterImageTiledFile)
RasterImageTiledFile.reset_number_swap = new_instancemethod(_raster_image_tiled_file.RasterImageTiledFile_reset_number_swap,None,RasterImageTiledFile)
RasterImageTiledFile_swigregister = _raster_image_tiled_file.RasterImageTiledFile_swigregister
RasterImageTiledFile_swigregister(RasterImageTiledFile)



