# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
from ._swig_wrap import _rsm_polynomial

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _rsm_polynomial.SWIG_PyInstanceMethod_New
_swig_new_static_method = _rsm_polynomial.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

SWIG_MODULE_ALREADY_DONE = _rsm_polynomial.SWIG_MODULE_ALREADY_DONE
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _rsm_polynomial.delete_SwigPyIterator
    value = _swig_new_instance_method(_rsm_polynomial.SwigPyIterator_value)
    incr = _swig_new_instance_method(_rsm_polynomial.SwigPyIterator_incr)
    decr = _swig_new_instance_method(_rsm_polynomial.SwigPyIterator_decr)
    distance = _swig_new_instance_method(_rsm_polynomial.SwigPyIterator_distance)
    equal = _swig_new_instance_method(_rsm_polynomial.SwigPyIterator_equal)
    copy = _swig_new_instance_method(_rsm_polynomial.SwigPyIterator_copy)
    next = _swig_new_instance_method(_rsm_polynomial.SwigPyIterator_next)
    __next__ = _swig_new_instance_method(_rsm_polynomial.SwigPyIterator___next__)
    previous = _swig_new_instance_method(_rsm_polynomial.SwigPyIterator_previous)
    advance = _swig_new_instance_method(_rsm_polynomial.SwigPyIterator_advance)
    __eq__ = _swig_new_instance_method(_rsm_polynomial.SwigPyIterator___eq__)
    __ne__ = _swig_new_instance_method(_rsm_polynomial.SwigPyIterator___ne__)
    __iadd__ = _swig_new_instance_method(_rsm_polynomial.SwigPyIterator___iadd__)
    __isub__ = _swig_new_instance_method(_rsm_polynomial.SwigPyIterator___isub__)
    __add__ = _swig_new_instance_method(_rsm_polynomial.SwigPyIterator___add__)
    __sub__ = _swig_new_instance_method(_rsm_polynomial.SwigPyIterator___sub__)
    def __iter__(self):
        return self

# Register SwigPyIterator in _rsm_polynomial:
_rsm_polynomial.SwigPyIterator_swigregister(SwigPyIterator)
SHARED_PTR_DISOWN = _rsm_polynomial.SHARED_PTR_DISOWN

import os

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_serialization(data):
    return geocal_swig.serialize_function.serialize_read_binary(data)

def _new_from_serialization_dir(dir, data):
    curdir = os.getcwd()
    try:
      os.chdir(dir)
      return geocal_swig.serialize_function.serialize_read_binary(data)
    finally:
      os.chdir(curdir)


def _new_vector(cls, version, lst):
    '''Create a vector from a list.'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    for i in lst:
       inst.append(i)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import geocal_swig.generic_object
class RsmPolynomial(geocal_swig.generic_object.GenericObject):
    r"""

    This is used to handle a single polynomial for use with a
    RsmRationalPolynomial.

    This is a low level class, you don't normally use this directly
    (although you certainly could if it was useful).

    Note we might want to consider making this a template based on the
    sizes so we can specialize/optimize the code. We'll see what the
    performance is like.

    C++ includes: rsm_polynomial.h 
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, Np_x, Np_y, Np_z, Is_denominator=False, Max_order=-1):
        r"""

        RsmPolynomial::RsmPolynomial(const RsmPolynomial &Rp)
        Copy constructor. 
        """
        _rsm_polynomial.RsmPolynomial_swiginit(self, _rsm_polynomial.new_RsmPolynomial(Np_x, Np_y, Np_z, Is_denominator, Max_order))
    __str__ = _swig_new_instance_method(_rsm_polynomial.RsmPolynomial___str__)
    check_zero_crossing = _swig_new_instance_method(_rsm_polynomial.RsmPolynomial_check_zero_crossing)
    __call__ = _swig_new_instance_method(_rsm_polynomial.RsmPolynomial___call__)
    jacobian_fitted_coefficent = _swig_new_instance_method(_rsm_polynomial.RsmPolynomial_jacobian_fitted_coefficent)
    jacobian = _swig_new_instance_method(_rsm_polynomial.RsmPolynomial_jacobian)
    set_rpc_coeff = _swig_new_instance_method(_rsm_polynomial.RsmPolynomial_set_rpc_coeff)
    _v_coefficient = _swig_new_instance_method(_rsm_polynomial.RsmPolynomial__v_coefficient)

    @property
    def coefficient(self):
        return self._v_coefficient()

    _v_fitted_coefficent = _swig_new_instance_method(_rsm_polynomial.RsmPolynomial__v_fitted_coefficent)

    @property
    def fitted_coefficent(self):
        return self._v_fitted_coefficent()

    @fitted_coefficent.setter
    def fitted_coefficent(self, value):
      self._v_fitted_coefficent(value)

    _v_is_denominator = _swig_new_instance_method(_rsm_polynomial.RsmPolynomial__v_is_denominator)

    @property
    def is_denominator(self):
        return self._v_is_denominator()

    _v_max_order = _swig_new_instance_method(_rsm_polynomial.RsmPolynomial__v_max_order)

    @property
    def max_order(self):
        return self._v_max_order()


    def __reduce__(self):
    #Special handling for when we are doing boost serialization, we set
    #"this" to None
      if(self.this is None):
        return super().__reduce__()
      return _new_from_serialization, (geocal_swig.serialize_function.serialize_write_binary(self),)

    __swig_destroy__ = _rsm_polynomial.delete_RsmPolynomial

# Register RsmPolynomial in _rsm_polynomial:
_rsm_polynomial.RsmPolynomial_swigregister(RsmPolynomial)

__all__ = ["RsmPolynomial"]


