[workspace]
authors = ["Mike Smyth <Mike.M.Smyth@jpl.nasa.gov>"]
channels = ["conda-forge", "/home/smyth/Local/afids-conda-package/afids-conda-channel"]
name = "build-pixi"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
afids = "*"
afids-development-tools = "*"
